server:
  port: 8001

spring:
  application:
    name: spring-cloud-eureka

eureka: 
  instance: 
    hostname: peer1
  client: 
    serviceUrl:
      defaultZone: http://peer2:8002/eureka/